sudo: false
language: python
matrix:
    fast_finish: true
    include:
        - python: "2.7"
          env: TOXENV=py27
        - python: "3.6"
          env: TOXENV=lint
install: pip install -U tox coveralls
script: tox
cache: pip
after_success: coveralls
